Basic commands/clone and init
eduardomacetas/learning-git pull request #1
Opened 2024-11-28 16:08 UTC by ginacardozo

This PR contains these files and its information:
- git-clone.md
- git-init.md

2024-11-28 16:17 UTC, eduardomacetas commented on 01-basic-commands/git-clone.md
> +La clonacion crea automaticamente una conexion remtoa llamada "origin" que apunta al repositorio original.
Puedes ponerle tilde a `clonación`

2024-11-28 16:19 UTC, ginacardozo commented on 01-basic-commands/git-clone.md
> +La clonacion crea automaticamente una conexion remtoa llamada "origin" que apunta al repositorio original.
recibido

2024-11-30 03:55 UTC, eduardomacetas commented on 01-basic-commands/git-clone.md
> +# Git CLone
Cambia "Git CLone" a "Git Clone"

2024-11-30 03:57 UTC, eduardomacetas commented on 01-basic-commands/git-clone.md
> +- git clone
Cambia la lista a un bloque de código para mayor claridad:

```bash
git clone
```

2024-11-30 03:59 UTC, eduardomacetas commented on 01-basic-commands/git-clone.md
> +## Buenas practicas (en caso exista)
¿Podrías eliminar esto?

2024-11-30 04:00 UTC, eduardomacetas commented on 01-basic-commands/git-clone.md
> +https://www.atlassian.com/es/git/tutorials/setting-up-a-repository/git-clone
Sería mejor presentar el enlace en formato de lista con un guion (-), ejemplo:

- Recurso 1
- Recurso 2
- Recurso 3

2024-11-30 04:01 UTC, eduardomacetas commented on 01-basic-commands/git-init.md
> +-
¿Podrías eliminar el guión?

2024-11-30 04:02 UTC, eduardomacetas commented on 01-basic-commands/git-init.md
> +1.
Completar la información 😄

2024-11-30 04:03 UTC, eduardomacetas requested changes
@ginacardozo  He dejado algunos comentarios

2024-12-10 01:00 UTC, ginacardozo commented on 01-basic-commands/git-clone.md
> +# Git CLone
Done

2024-12-10 18:46 UTC, eduardomacetas approved these changes

2024-12-10 18:47 UTC, merged